# Generated by Django 4.2 on 2025-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_status",
            field=models.CharField(
                default="inactive",
                help_text="Tracks the latest status returned by Stripe for this user's checkout session.",
                max_length=50,
            ),
        ),
    ]
