# Generated by Django 4.2 on 2025-12-13 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_is_premium_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hearts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hearts_last_refill_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
