# Generated by Django 4.2 on 2024-11-27 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='user',
        ),
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
