# Generated by Django 4.2 on 2024-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='missioncompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
