# Generated by Django 5.1.2 on 2024-11-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
