# Generated by Django 4.2 on 2024-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lesson_detailed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
