# Generated by Django 5.1.2 on 2024-11-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_content_lesson_detailed_content_lesson_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_lessons',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='core.lesson'),
        ),
    ]
