# Generated by Django 5.1.2 on 2024-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userprogress_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
