# Generated by Django 4.2 on 2025-12-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("complete", "Complete"),
                            ("hint", "Hint"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="education.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercise_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exerciseevent",
            index=models.Index(
                fields=["exercise", "event_type", "created_at"],
                name="analytics_e_exercis_76e4e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseevent",
            index=models.Index(
                fields=["session_id", "created_at"],
                name="analytics_e_session_7bd4f7_idx",
            ),
        ),
    ]
