# Generated by Django 4.2 on 2025-12-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_userprogress_flow_current_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("explanation", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_choices",
                        to="education.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "core_multiplechoicechoice",
                "ordering": ["order", "id"],
            },
        ),
    ]
