# Generated by Django 4.2 on 2025-12-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="faq",
            constraint=models.CheckConstraint(
                check=models.Q(helpful_count__gte=0),
                name="faq_helpful_count_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="faq",
            constraint=models.CheckConstraint(
                check=models.Q(not_helpful_count__gte=0),
                name="faq_not_helpful_count_gte_0",
            ),
        ),
    ]


