# Generated by Django 4.2 on 2024-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('basic_finance', 'Basic Finance'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('forex', 'Forex')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
