# Generated by Django 4.2 on 2025-01-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
