# Generated by Django 4.2 on 2025-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_email_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wants_personalized_path',
            field=models.BooleanField(default=False),
        ),
    ]
