# Generated by Django 4.2 on 2024-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_generated_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
