# Generated by Django 4.2 on 2025-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_image_alter_mission_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='path_images/'),
        ),
    ]
