# Generated by Django 5.1.4 on 2025-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lesson_exercise_data_lesson_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('drag-and-drop', 'Drag and Drop'), ('multiple-choice', 'Multiple Choice'), ('quiz', 'Quiz')], max_length=50, null=True),
        ),
    ]
