# Generated by Django 4.2 on 2025-11-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_financialgoal'),
    ]

    operations = [
    ]
