# Generated by Django 4.2 on 2025-01-19 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_mission_goal_id_mission_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='mission',
            name='goal_reference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='goal_type',
            field=models.CharField(choices=[('complete_lesson', 'Complete Lesson'), ('complete_exercise', 'Complete Exercise'), ('complete_course', 'Complete Course'), ('read_fact', 'Read Finance Fact'), ('add_savings', 'Add Savings')], default='complete_lesson', max_length=50),
        ),
        migrations.AlterField(
            model_name='missioncompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_completions', to=settings.AUTH_USER_MODEL),
        ),
    ]
