# Generated by Django 4.2 on 2025-01-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_simulatedsavingsaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='goal_type',
            field=models.CharField(choices=[('complete_lesson', 'Complete Lesson'), ('add_savings', 'Add Savings'), ('read_fact', 'Read Finance Fact')], default='complete_lesson', max_length=50),
        ),
    ]
