# Generated by Django 4.2 on 2025-03-07 19:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exercise_userexerciseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text Content'), ('video', 'Video'), ('exercise', 'Interactive Exercise')], default='text', max_length=20)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('exercise_data', models.JSONField(blank=True, null=True)),
                ('is_interactive', models.BooleanField(default=False)),
                ('estimated_duration', models.PositiveIntegerField(default=120, help_text='Duration in seconds')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
