# Generated by Django 4.2 on 2025-03-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lessonsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsection',
            name='is_interactive',
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.CreateModel(
            name='SectionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessonsection')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprogress')),
            ],
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_sections',
            field=models.ManyToManyField(blank=True, through='core.SectionCompletion', to='core.lessonsection'),
        ),
    ]
