# Generated by Django 4.2 on 2025-03-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_lessonsection_is_interactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonsection',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='lessonsection',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('drag-and-drop', 'Drag and Drop'), ('multiple-choice', 'Multiple Choice'), ('budget-allocation', 'Budget Allocation')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsection',
            unique_together={('lesson', 'order')},
        ),
        migrations.RemoveField(
            model_name='lessonsection',
            name='estimated_duration',
        ),
    ]
