# Generated by Django 4.2 on 2025-03-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_content_lessonsection_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonsection',
            old_name='text_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='lessonsection',
            name='exercise_type',
        ),
    ]
