# Generated by Django 4.2 on 2025-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_text_content_lessonsection_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonsection',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='lessonsection',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('drag-and-drop', 'Drag and Drop'), ('multiple-choice', 'Multiple Choice'), ('budget-allocation', 'Budget Allocation')], max_length=50, null=True),
        ),
    ]
