# Generated by Django 4.2 on 2025-03-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_content_lessonsection_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('investing', 'Investing'), ('budgeting', 'Budgeting'), ('credit', 'Credit'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('preference', 'Preference'), ('knowledge_check', 'Knowledge Check'), ('poll', 'Poll'), ('demographic', 'Demographic')], default='preference', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
    ]
