# Generated by Django 4.2 on 2025-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_question_is_active_alter_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('knowledge_check', 'Knowledge Check'), ('preference_scale', 'Preference Scale'), ('poll', 'Community Poll'), ('budget_allocation', 'Budget Allocation')], max_length=20),
        ),
    ]
