# Generated by Django 4.2 on 2025-03-09 17:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_question_required_remove_question_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=jsonfield.fields.JSONField(),
        ),
    ]
