# Generated by Django 5.1.7 on 2025-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_exercisecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
