# Generated by Django 5.1.7 on 2025-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
